=== Toropoff/Api-testing-framework-module/test-suites/tests-public-api/src/test/resources/schemas/public-holidays-by-date.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id", "name", "country", "type", "nationwide", "regionalScope", "temporalScope"],
    "properties": {
      "id":            { "type": "string" },
      "name":          { "type": "array" },
      "country":       {
        "type": "object",
        "required": ["isoCode"],
        "properties": { "isoCode": { "type": "string" } }
      },
      "type":          { "type": "string" },
      "nationwide":    { "type": "boolean" },
      "startDate":     { "type": "string" },
      "endDate":       { "type": "string" },
      "subdivisions":  { "type": ["array", "null"] },
      "groups":        { "type": ["array", "null"] },
      "regionalScope": { "type": "string" },
      "temporalScope": { "type": "string" },
      "comment":       { "type": ["array", "null"] },
      "tags":          { "type": ["array", "null"] }
    }
  }
}

=== Toropoff/Api-testing-framework-module/test-suites/tests-public-api/src/test/resources/snapshots/school-holidays-by-date.json
[
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "FR"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Easter holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "FR-GY",
        "shortName": "GY"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "ZA"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Summer Break"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "FR"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas Holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "FR-YT",
        "shortName": "YT"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "PT"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "MX"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "DE"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas Holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "DE-SH",
        "shortName": "SH"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "IE"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "ES"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "ES-AR",
        "shortName": "AR"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "FR"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Southern summer holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "FR-RU",
        "shortName": "RU"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "DE"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas Holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "DE-HH",
        "shortName": "HH"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-FR",
        "shortName": "FR"
      }
    ],
    "comment": [
      {
        "language": "FR",
        "text": "Écoles sec. II"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "MC"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-BE",
        "shortName": "BE"
      }
    ],
    "groups": [
      {
        "code": "CH-BE-VS",
        "shortName": "BE-VS"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-VD",
        "shortName": "VD"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-TI",
        "shortName": "TI"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-VS",
        "shortName": "VS"
      }
    ],
    "comment": [
      {
        "language": "EN",
        "text": "German-speaking"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-GR-MS",
        "shortName": "GR-MS"
      }
    ],
    "groups": [
      {
        "code": "CH-GR-VS",
        "shortName": "GR-VS"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-VS",
        "shortName": "VS"
      }
    ],
    "comment": [
      {
        "language": "EN",
        "text": "French-speaking"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-UR",
        "shortName": "UR"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "BG"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-GR-VM",
        "shortName": "GR-VM"
      },
      {
        "code": "CH-GR-ML",
        "shortName": "GR-ML"
      },
      {
        "code": "CH-GR-EB",
        "shortName": "GR-EB"
      },
      {
        "code": "CH-GR-IB",
        "shortName": "GR-IB"
      },
      {
        "code": "CH-GR-SS",
        "shortName": "GR-SS"
      },
      {
        "code": "CH-GR-BN",
        "shortName": "GR-BN"
      },
      {
        "code": "CH-GR-PD",
        "shortName": "GR-PD"
      },
      {
        "code": "CH-GR-PS",
        "shortName": "GR-PS"
      },
      {
        "code": "CH-GR-LQ",
        "shortName": "GR-LQ"
      },
      {
        "code": "CH-GR-AB",
        "shortName": "GR-AB"
      }
    ],
    "groups": [
      {
        "code": "CH-GR-VS",
        "shortName": "GR-VS"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-LU",
        "shortName": "LU"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "CH"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas and New Year holidays"
      }
    ],
    "regionalScope": "Regional",
    "temporalScope": "FullDay",
    "nationwide": false,
    "subdivisions": [
      {
        "code": "CH-GE",
        "shortName": "GE"
      }
    ]
  },
  {
    "id": "${json-unit.ignore}",
    "country": {
      "isoCode": "LI"
    },
    "type": "School",
    "name": [
      {
        "language": "EN",
        "text": "Christmas holidays"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
